services:
  - type: web
    name: reconcile-backend
    env: python
    buildCommand: pip install fastapi uvicorn[standard] sqlmodel
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: reconcile-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false
